name: Generate Snake Animation

on:
  schedule:
    # Runs at midnight every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: muditbhatt-5
          outputs: dist/github-contribution-grid-snake.svg
      - name: Upload snake animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
      - name: Commit and push animation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake animation"
          git push
